FROM python:3.11-buster as builder

RUN pip install poetry==1.4.2

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

COPY pyproject.toml ./

RUN poetry lock

RUN touch README.md

RUN poetry install --no-root && rm -rf $POETRY_CACHE_DIR

FROM python:3.11-slim-buster as runtime





# ENV VIRTUAL_ENV=/app/.venv \
    # PATH="/app/.venv/bin:$PATH"

WORKDIR /app

COPY --from=builder /app/.venv ./.venv

ENV PATH="/app/.venv/bin:$PATH"


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y \  
  netcat \
  curl \
  build-essential \
  && rm -rf /var/lib/apt/lists/*

# Instalar Node.js (LTS) y npm
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs


COPY manage.py .

COPY ./entrypoint.sh .

RUN sed -i 's/\r$//g' ./entrypoint.sh

RUN chmod +x ./entrypoint.sh

ARG gid=1001
ARG uid=1001
ARG user=lunaruser
ARG group=docker



RUN groupadd -g ${gid} ${group} && \
    useradd -u ${uid} -g ${group} -s /bin/bash -m ${user}


# Cambiar al usuario creado
USER ${user}




ENTRYPOINT ["./entrypoint.sh"]

