services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=josue
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=pasarelaDevelopment
    volumes:
      - postgres_data:/var/lib/postgresql/data
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        gid: ${GROUPID}
        uid: ${USERID}

    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn src.core.wsgi:application --reload --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
    expose:
      # - "8000:8000"
      - 8000
    volumes:
      - /home/chamba/Desktop/py/pasarelaBackend/src:/app/src
      - /home/chamba/Desktop/py/pasarelaBackend/static:/app/static
      - shared-volume:/app/.venv

  lunarvim:
    build:
      context: .
      dockerfile: Dockerfile.lunarvim  # Usa el Dockerfile específico para LunarVim
      args:
        gid: ${GROUPID}
        uid: ${USERID}
    environment:
      - DISPLAY=${DISPLAY}
    container_name: lunarvim_container # Nombre del contenedor
    depends_on:
      - dev
    volumes:
      - .:/home/lunaruser/project      # Monta el directorio actual en el contenedor
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home/chamba/.config/lvim:/home/lunaruser/.config/lvim
      - shared-volume:/home/lunaruser/project/.venv
    tty: true
    stdin_open: true
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 1337:80
    depends_on:
      - dev
volumes:
  postgres_data:
  shared-volume:
    
