services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=josue
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=pasarelaProduction
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    networks:
      # Conecta el servicio postgres a la nueva red interna para comunicarse con la aplicación
      - db_network
  prod:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.prod
    image: urgosxd7/pasarelabackend
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn src.core.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env.prod
    expose:
      - 8000
    
    networks:
      # Conecta el servicio payloaubd a la red externa para comunicarse con el proxy
      - proxiable
      # Conecta el servicio payload a la nueva red interna para comunicarse con la base de datos
      - db_network
volumes:
  postgres_data:

networks:
  proxiable:
    external: true
    name: proxiable
  
  db_network:
    driver: bridge
