services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=josue
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=pasarelaProduction
    volumes:
      - postgres_data:/var/lib/postgresql/data
  prod:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.prod
    image: urgosxd7/pasarelabackend
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn src.core.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env.prod
    expose:
      - 8000
volumes:
  postgres_data:

networks:
  default:
    external: true
    name: proxiable
