services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=josue
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=pasarelaDevelopment
    volumes:
      - postgres_data:/var/lib/postgresql/data
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        gid: ${GROUPID}
        uid: ${USERID}

    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn src.core.wsgi:application --reload --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
    expose:
      # - "8000:8000"
      - 8000
    volumes:
      - /home/chamba/Desktop/py/pasarelaBackend/src:/app/src
      - /home/chamba/Desktop/py/pasarelaBackend/static:/app/static
      - shared-volume:/app/.venv

volumes:
  postgres_data:
  shared-volume:
    
