# Generated by Django 5.1.3 on 2024-12-02 17:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTienda', models.CharField(max_length=255, verbose_name='Id tienda')),
                ('password', models.CharField(max_length=255, verbose_name='Password Tienda')),
                ('hmacSha256', models.CharField(max_length=255, verbose_name='Clave HMAC-SHA-256 ')),
            ],
        ),
        migrations.CreateModel(
            name='DataGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminosyCondiciones', wagtail.fields.RichTextField(blank=True, verbose_name='Terminos y Condiciones')),
            ],
        ),
        migrations.CreateModel(
            name='DataPasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePassenger', models.CharField(max_length=255, verbose_name='Nombre del Pasajero')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo Electronico')),
                ('namePaquete', models.CharField(max_length=255, verbose_name='Nombre del Paquete')),
                ('unitaryPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio')),
                ('finalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio Final')),
                ('unitaryPriceSub1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio Final Sub1')),
                ('unitaryPriceSub2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio Final Sub2')),
                ('referiCode', models.CharField(max_length=255, verbose_name='Codigo de Referido')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Link Creado')),
            ],
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
