# Generated by Django 5.1.3 on 2024-12-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapasajero',
            name='percentaje',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
