# Generated by Django 5.1.3 on 2024-11-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePassenger', models.CharField(max_length=255, verbose_name='Nombre del Pasajero')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo Electronico')),
                ('namePaquete', models.CharField(max_length=255, verbose_name='Nombre del Paquete')),
                ('unitaryPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio')),
            ],
        ),
    ]
