# Generated by Django 5.1.3 on 2024-12-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_datapasajero_percentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapasajero',
            name='numPasajeros',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
