# Generated by Django 5.1.3 on 2024-11-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_datapasajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapasajero',
            name='referiCode',
            field=models.CharField(default='nada', max_length=255, verbose_name='Codigo de Referido'),
            preserve_default=False,
        ),
    ]
