# Generated by Django 5.1.3 on 2024-12-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_datapasajero_numpasajeros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapasajero',
            name='finalPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Precio Final'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='numPasajeros',
            field=models.IntegerField(verbose_name='Numero de Pasajeros'),
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='percentaje',
            field=models.IntegerField(verbose_name='Porcentage'),
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='unitaryPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='unitaryPriceSub1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Precio Final a Pagar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='unitaryPriceSub2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Precio Final por Pagar'),
            preserve_default=False,
        ),
    ]
