# Generated by Django 5.1.3 on 2024-11-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_datapasajero_refericode'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapasajero',
            name='finalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio Final'),
        ),
        migrations.AddField(
            model_name='datapasajero',
            name='unitaryPriceSub1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio Final Sub1'),
        ),
        migrations.AddField(
            model_name='datapasajero',
            name='unitaryPriceSub2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio Final Sub2'),
        ),
    ]
