# Generated by Django 5.1.3 on 2024-11-28 04:39

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_datapasajero_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminosyCondiciones', wagtail.fields.RichTextField(blank=True)),
                ('idTienda', models.CharField(max_length=255, verbose_name='Id tienda')),
                ('password', models.CharField(max_length=255, verbose_name='Password Tienda')),
            ],
        ),
    ]
