# Generated by Django 5.1.3 on 2025-01-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_apis_hmacsha256_apis_paypalclientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapasajero',
            name='email',
            field=models.EmailField(max_length=500, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link Creado'),
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='namePaquete',
            field=models.CharField(max_length=500, verbose_name='Nombre del Paquete'),
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='namePassenger',
            field=models.CharField(max_length=500, verbose_name='Nombre del Pasajero'),
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='referiCode',
            field=models.CharField(max_length=500, verbose_name='Codigo de Referido'),
        ),
    ]
