# Generated by Django 5.1.3 on 2025-03-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_datapasajero_email_alter_datapasajero_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapasajero',
            name='numPasajerosInfante',
            field=models.IntegerField(default=0, verbose_name='Numero de Pasajeros Infantes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapasajero',
            name='numPasajerosMenor',
            field=models.IntegerField(default=0, verbose_name='Numero de Pasajeros Menores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapasajero',
            name='unitaryPriceInfante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio Infante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapasajero',
            name='unitaryPriceMenor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio Menor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='numPasajeros',
            field=models.IntegerField(verbose_name='Numero de Pasajeros Adultos'),
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='unitaryPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Adulto'),
        ),
    ]
