# Generated by Django 5.1.3 on 2025-03-15 16:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_datapasajero_numpasajerosinfante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datageneral',
            name='terminosyCondicionesEng',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Terminos y Condiciones Ingles'),
        ),
    ]
