# Generated by Django 5.1.3 on 2025-03-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_datageneral_terminosycondicioneseng'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapasajero',
            name='link2',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link Creado EN'),
        ),
        migrations.AlterField(
            model_name='datapasajero',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link Creado ES'),
        ),
    ]
