# Generated by Django 5.1.3 on 2025-03-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_datapasajero_link2_alter_datapasajero_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteMexico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePaquete', models.CharField(max_length=500, verbose_name='Nombre del Paquete')),
                ('unitaryPriceAdultAfter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Adulto Antes')),
                ('unitaryPriceMenorAfter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Menor Antes')),
                ('unitaryPriceAdultIn', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Adulto Durante')),
                ('unitaryPriceMenorIn', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Menor Durante')),
                ('unitaryPriceAdultBefore', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Adulto Despues')),
                ('unitaryPriceMenorBefore', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Menor Despues')),
                ('percentaje', models.IntegerField(verbose_name='Porcentage')),
                ('fechas', models.CharField(max_length=500, verbose_name='Fechas')),
            ],
        ),
    ]
