# Generated by Django 5.1.3 on 2025-03-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_paquetemexico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetemexico',
            name='unitaryPriceChildAfter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio Ninio Antes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquetemexico',
            name='unitaryPriceChildBefore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio Ninio Despues'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquetemexico',
            name='unitaryPriceChildIn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio Ninio Antes'),
            preserve_default=False,
        ),
    ]
