name: Test secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - name: Check VPS_IP
        run: |
          if [ -z "${{ secrets.VPS_IP }}" ]; then
            echo "❌ VPS_IP is missing"
            exit 1
          else
            echo "✅ VPS_IP is set"
          fi

      - name: Check VPS_USERNAME
        run: |
          if [ -z "${{ secrets.VPS_USERNAME }}" ]; then
            echo "❌ VPS_USERNAME is missing"
            exit 1
          else
            echo "✅ VPS_USERNAME is set"
          fi

      - name: Check VPS_SSH_KEY
        run: |
          if [ -z "${{ secrets.VPS_SSH_KEY }}" ]; then
            echo "❌ VPS_SSH_KEY is missing"
            exit 1
          else
            echo "✅ VPS_SSH_KEY is set"
          fi
